import Head from "next/head";
import Navbar from "../components/Navbar/Navbar.js";
import React, { useEffect } from "react";
import { useSelector, useDispatch } from "react-redux";
// STATE
import { checkScreenSize } from "../State/hideAnimationSlice";

export default function Home() {
  const dispatch = useDispatch();
  // Check screen size on page load
  useEffect(() => {
    dispatch(checkScreenSize());
  }, [dispatch]);
  return (
    <div className="layout">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <h1>HELLO </h1>
    </div>
  );
}
